use Addr;
use system::memory::{ptr, read};

#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Flag(pub Addr, pub u8);

macro_rules! flags {
    ($($name:ident: $addr:expr, $bit:expr)*) => {
        $(
            pub const $name: Flag = Flag(0x803B8700 | $addr, 1 << $bit);
        )*
    };
}

flags! {
    HAS_SEEN_HELMAROC_ARRIVING_AT_OUTSET: 0x2C, 0
    TALKED_TO_ORCA_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x2C, 1
    FOREST_OF_FAIRIES_BOKOBLINS_SPAWNED: 0x2C, 2
    TALKED_TO_ABE_ON_OUTSET_AFTER_HELMAROC: 0x2C, 3
    TALKED_TO_MESA_ON_OUTSET_WITH_SWORD: 0x2C, 4
    TALKED_TO_MESA_ON_OUTSET_WITHOUT_SWORD: 0x2C, 5
    TALKED_TO_ABE_ON_OUTSET_BEFORE_HELMAROC: 0x2C, 7
    RESCUED_TETRA: 0x2D, 0
    GOT_A_RUPEE_ON_THE_OUTSET_ROCKS: 0x2D, 2
    TALKED_TO_ORCA_AFTER_HELMAROC_ARRIVED: 0x2D, 3
    TALKED_TO_SUE_BELLE_WITH_PIRATES_ON_OUTSET: 0x2D, 5
    TALKED_TO_SUE_BELLE_ON_OUTSET_AFTER_HELMAROC: 0x2D, 6
    TALKED_TO_SUE_BELLE_ON_OUTSET_BEFORE_HELMAROC: 0x2D, 7
    SAW_A_LIGHT_OPERATOR_BOKOBLIN: 0x2E, 0
    TALKED_TO_JOEL_ON_OUTSET: 0x2E, 4
    TALKED_TO_ZILL_ON_OUTSET_EAST: 0x2E, 5
    TALKED_TO_KIDS_WITH_PIRATES_ON_OUTSET: 0x2E, 6
    SAW_TETRA_IN_FOREST_OF_FAIRIES: 0x2E, 7
    KILLED_ONE_FOREST_OF_FAIRIES_BOKOBLIN: 0x2F, 0
    BROUGHT_BACK_1_PIG_TO_ROSE_ON_OUTSET: 0x2F, 1
    TALKED_TO_ROSE_ON_OUTSET_2: 0x2F, 2
    TALKED_TO_ROSE_WITH_PIRATES_ON_OUTSET: 0x2F, 3 // Unsure if actually Rose
    PIRATE_SHIP_ARRIVING_ON_OUTSET: 0x2F, 4
    SAW_LAVA_PLATFORMS_FORMING: 0x2F, 7
    PICKED_UP_FIRST_BARREL_IN_FF1: 0x30, 0 // Don't show Jail Text anymore
    GRABBED_FIRST_ROPE_IN_FF1: 0x30, 1
    GOT_THROWN_INTO_JAIL_IN_FF1: 0x30, 2
    GRAPPLED_VALOOS_TAIL: 0x30, 5
    KILLED_BOTH_FOREST_OF_FAIRIES_BOKOBLINS: 0x30, 7
    BONKED_ORCAS_WALL: 0x31, 0
    VISITED_STURGEON_ON_OUTSET_BEGIN: 0x31, 1
    VISITED_STURGEON_ON_OUTSET_END: 0x31, 3
    TALKED_TO_STURGEON_ON_OUTSET_BEFORE_HELMAROC: 0x31, 4
    GOSSIP_STONE_AT_FF1: 0x31, 5
    GRAPPLED_VALOOS_TAIL_2: 0x31, 6
    USED_GRAPPLING_HOOK: 0x31, 7
    TALKED_TO_GRANDMA_AFTER_SEEING_HELMAROC: 0x32, 0
    TALKED_TO_GRANDMA_AFTER_GETTING_SWORD: 0x32, 1
    TALKED_TO_OLIVIO_IN_FOREST_HAVEN: 0x32, 2
    VISITED_ORCA_BEFORE_HELMAROC: 0x32, 6
    TALKED_TO_MAKO_ON_SAILING_PIRATE_SHIP: 0x33, 0
    TALKED_TO_ZUKO_ON_SAILING_PIRATE_SHIP: 0x33, 1
    TALKED_TO_NIKO_AFTER_MINIGAME: 0x33, 2
    COMPLETED_PIRATE_SHIP_MINIGAME: 0x33, 4
    SAW_PIRATE_SHIP_MINIGAME_INTRO: 0x33, 5
    TALKED_TO_GRANDMA_AFTER_ARYLL_GOT_CAPTURED: 0x33, 6
    GOT_CATAPULTED_TO_FF1_AND_SPAWN_THERE: 0x34, 0
    LONG_TETRA_TEXT_ON_OUTSET: 0x34, 1
    TETRA_TOLD_YOU_TO_CLIMB_UP_THE_LADDER: 0x34, 2
    COMPLETED_PIRATE_SHIP_MINIGAME_AND_SPAWN_ON_PIRATE_SHIP: 0x34, 3
    TALKED_TO_TETRA_ON_SAILING_PIRATE_SHIP: 0x34, 4
    TALKED_TO_NUDGE_ON_SAILING_PIRATE_SHIP: 0x34, 5
    TALKED_TO_SENZA_ON_SAILING_PIRATE_SHIP: 0x34, 6
    TALKED_TO_GONZO_ON_SAILING_PIRATE_SHIP: 0x34, 7
    TRIGGERED_MAP_FISH: 0x35, 0
    SAW_DRAGON_ROOST_ISLAND_INTRO: 0x35, 1
    SAIL_INTRODUCTION_TEXT_AND_MAP_UNLOCKED: 0x35, 3
    TALKED_TO_GONZO_ON_OUTSET_BEACH: 0x35, 4
    TALKED_TO_ALDO_IN_FOREST_HAVEN: 0x35, 5
    TALKED_TO_NIKO_ON_OUTSET_BEACH: 0x35, 6
    TALKED_TO_KORL_AT_GREATFISH: 0x36, 0
    ENDLESS_NIGHT: 0x36, 1
    TALKED_TO_KORL_AFTER_LEAVING_FH: 0x36, 3
    TALKED_TO_KORL_ON_DRI: 0x36, 4
    WATCHED_FOREST_HAVEN_INTRO_CUTSCENE: 0x36, 5
    TALKED_TO_POMPIE_AND_VERA_ON_WINDFALL: 0x36, 6
    KORL_DINS_PEARL_TEXT_ALLOWING_YOU_TO_ENTER_HIM: 0x36, 7
    TALKED_TO_ABE_WITH_PIRATES_ON_OUTSET: 0x37, 0
    TALKED_POSITIVELY_TO_MILAS_FATHER_ON_WINDFALL: 0x37, 1
    TALKED_POSITIVELY_TO_MAGGIES_FATHER_ON_WINDFALL: 0x37, 2
    TALKED_TO_TOTT_ON_WINDFALL: 0x37, 3
    HURRICANE_SPIN_UNLOCKED: 0x37, 5
    TALKED_TO_TINGLE_IN_JAIL: 0x37, 6
    RESCUED_TINGLE: 0x37, 7
    TALKED_TO_ROWN_IN_FOREST_HAVEN: 0x38, 1
    TALKED_TO_IRCH_IN_FOREST_HAVEN: 0x38, 2
    TALKED_TO_DRONA_IN_FOREST_HAVEN: 0x38, 3
    TALKED_TO_LINDER_IN_FOREST_HAVEN: 0x38, 4
    TALKED_TO_OAKIN_IN_FOREST_HAVEN: 0x38, 5
    TALKED_TO_HOLLO_IN_STORE_IN_FOREST_HAVEN: 0x39, 3
    TALKED_TO_ELMA_OUTSIDE_FOREST_HAVEN: 0x39, 6
    SHOW_ORCA_KNIGHTS_CREST: 0x39, 7
    WATCHED_LIGHT_BRIDGE_IN_TOTG_APPEAR: 0x3A, 0
    GOT_KOMALIS_LETTER: 0x3A, 1
    PLAYED_SPLOOSH_KABOOM_WELL: 0x3A, 2
    PIRATES_ON_OUTSET: 0x3A, 5
    TALKED_TO_DEKU_TREE_AFTER_LEAF_CUTSCENE: 0x3A, 6
    TETRA_GOSSIP_STONE_TEXT_AFTER_BOMBS: 0x3B, 1
    TALKED_TO_KOMALI_AFTER_SHOWING_THE_LETTER: 0x3B, 2
    TALKED_TO_KOMALI_WITHOUT_THE_LETTER: 0x3B, 3
    WATCHED_LIGHT_BRIDGE_IN_TOTG_DISAPPEAR: 0x3B, 6
    KORL_UNLOCKED_AND_SPAWN_ON_WINDFALL: 0x3B, 7
    WATCHED_FIRE_AND_ICE_ARROWS_CUTSCENE: 0x3C, 0
    GOT_GRAPPLING_HOOK_FROM_MEDLI: 0x3D, 0
    GOT_BOTTLE_FROM_MEDLI: 0x3D, 1
    TALKED_TO_MEDLI_IN_THE_POND: 0x3D, 2
    TALKED_TO_DOC_BANDAM_ON_WINDFALL: 0x3D, 5
    RESCUED_MEDLI_IN_DRC: 0x3D, 6
    TALKED_TO_JUN_ROBERTO_ON_WINDFALL: 0x3E, 0
    TALKED_TO_JIN_ON_WINDFALL: 0x3E, 1
    TALKED_TO_JAN_ON_WINDFALL: 0x3E, 2
    TALKED_TO_LENZO_ON_WINDFALL_WITHOUT_CAMERA: 0x3E, 3
    TALKED_TO_IVAN_ON_WINDFALL: 0x3E, 4
    MEDLI_EXPLAINED_GRAPPLING_HOOK: 0x3E, 7
    AGREED_TO_HELP_MRS_MARIE: 0x3F, 7
    TALKED_TO_QUILL_ON_OUTSET_BEACH: 0x40, 0
    WATCHED_MEDLI_ON_DRI_INTRODUCTION_CUTSCENE: 0x40, 1
    TALKED_TO_NICO_AFTER_GOSIP_TEXT_AFTER_BOMBS: 0x41, 1
    SHOWED_MEDLI_THE_WIND_WAKER_ON_DRI: 0x41, 2
    TALKED_TO_ALL_THE_KIDS_ON_WINDFALL: 0x42, 1
    HAS_MAKAR_ON_BOAT_1: 0x42, 2
    HAS_MEDLI_ON_BOAT_1: 0x42, 3
    HAS_MAKAR_ON_BOAT_2_AND_IS_GRABBABLE: 0x42, 4
    HAS_MEDLI_ON_BOAT_2_AND_CAN_CARRY_YOU: 0x42, 5
    TALKED_TO_LENZO_ON_WINDFALL_WITH_CAMERA: 0x43, 0
    WATCHED_DEKU_TREE_CUTSCENE: 0x44, 0
    TALKED_TO_RITO_LEADER_AFTER_DRC: 0x44, 1
    SAW_KOMALI_IN_HIS_ROOM: 0x44, 4
    TALKED_TO_MAKAR_POST_KALLE_DEMOS: 0x45, 2
    TALKED_TO_KORL_AFTER_HYRULE_2_AND_FF3_ACTIVE: 0x44, 5
    ENTERED_THE_PASSWORD_ON_PIRATE_SHIP: 0x45, 4
    IS_ALLOWED_TO_ENTER_KORL: 0x45, 7
    STARTED_MAIL_MINIGAME: 0x46, 0
    MAIL_MINIGAME_INTRO: 0x46, 1
    TALKED_TO_NICO_BEFORE_ROPE_GAME_2: 0x46, 2
    LEFT_DRAGON_ROOST_ISLAND_QUADRANT: 0x46, 7 // Potentially time being able to pass?
    TALKED_TO_GOSSACK_ON_WINDFALL: 0x47, 2
    WATCHED_FARORES_PEARL_CUTSCENE: 0x48, 5
    LEAVING_FOREST_HAVEN_WITH_PEARL: 0x48, 6
    TALKED_TO_HOLLO_AFTER_FORBIDDEN_WOODS: 0x48, 7
    TALKED_TO_MINENCO_ON_WINDFALL: 0x49, 4
    TALKED_TO_MISSY_ON_WINDFALL: 0x49, 5
    TALKED_TO_MRS_MARIE_ON_WINDFALL: 0x4A, 0
    TALKED_TO_GARRICKSON_ON_WINDFALL: 0x4A, 3
    TALKED_TO_GILLIAN_ON_WINDFALL: 0x4A, 5
    TOWER_OF_THE_GODS_RAISED: 0x4A, 6
    QUILL_TELLS_US_JABUN_IS_HIDING_AT_OUTSET: 0x4A, 7
    TALKED_TO_KORL_AFTER_GETTING_BOMBS: 0x4B, 1
    WATCHED_WINDFALL_PIRATE_CUTSCENE: 0x4B, 2
    SAW_QUILL_CUTSCENE_ON_DRI: 0x4B, 6
    TALKED_TO_LINDA_ON_WINDFALL: 0x4D, 0
    LISTENED_TO_PIRATES_IN_BOMB_SHOP: 0x4D, 4
    TALKED_TO_RITO_OUTSIDE_MEDLI_ROOM: 0x4D, 5 //Check Name
    TALKED_TO_ANTON_ON_WINDFALL: 0x4E, 3
    TALKED_TO_GUMMY_ON_WINDFALL: 0x4F, 1
    WATCHED_DEPARTURE_CUTSCENE_AND_SPAWN_ON_PIRATE_SHIP: 0x50, 0
    TALKED_TO_ZUNARI_ON_WINDFALL: 0x50, 5
    TALKED_TO_DAMPA_ON_WINDFALL: 0x50, 6
    TALKED_TO_SAM_ON_WINDFALL: 0x51, 0
    GOT_DELIVERY_BAG: 0x51, 1
    PLAYED_SPLOOSH_KABOOM: 0x51, 6
    WATCHED_FIND_SISTER_IN_FF1_CUTSCENE: 0x51, 7
    PICKED_UP_STATUE_IN_TOTG_FLOOR_1: 0x52, 1
    GOT_NOTE_TO_MOM: 0x53, 0
    SAID_YES_TO_BAITO_FIRST_TIME: 0x53, 1 //That you were "the one" that was good at sorting mail
    TALKED_TO_BAITO_AT_MINIGAME: 0x53, 2
    LEARNED_WINDS_REQUIEM: 0x53, 3 // Doesn't trigger if you do Zephos Skip
    SOME_WEIRD_FIRE_AND_ICE_ARROWS_CUTSCENE_FLAG: 0x53, 6
    MADE_MILAS_FATHER_ANGRY: 0x53, 7
    TALKED_TO_JOANNA_ON_WINDFALL: 0x54, 7
    GOT_LEAF: 0x55, 1
    TALKED_TO_MESA_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x55, 2
    DENIED_LEAVING_OUTSET: 0x55, 3
    MAKAR_IN_WIND_TEMPLE: 0x55, 4
    MEDLI_IN_EARTH_TEMPLE: 0x55, 5
    ENTERED_KORL_AFTER_GREATFISH: 0x56, 0
    ENTERED_KORL_AFTER_FORBIDDEN_WOODS: 0x56, 1 // Maybe visit any quadrant?
    ENTER_KORL_FOR_THE_FIRST_TIME_AND_SPAWN_ANYWHERE: 0x56, 3
    CUT_ALL_ROPES_HOLDING_PLATFORM_IN_DRC: 0x56, 4
    GRANDMA_IS_CURED: 0x56, 5
    HAS_HEROS_CLOTHES: 0x56, 7
    TALKED_TO_POTOVA_ON_WINDFALL: 0x57, 3
    DESTROY_VINE_ON_DOOR_IN_FORBIDDEN_WOODS: 0x57, 5
    TALKED_TO_KORL_AFTER_FH_CUTSCENE: 0x57, 7
    MIGHTY_DARKNUTS_DEFEATED: 0x58, 0
    BARRIER_DOWN: 0x58, 1
    TALKED_TO_ROSE_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x58, 5
    TALKED_TO_ROSE_ON_OUTSET_1: 0x58, 7
    ANIMATION_SET_2: 0x59, 0
    TETRA_TO_ZELDA_CUTSCENE: 0x59, 1
    MASTER_SWORD_CUTSCENE: 0x59, 2
    HYRULE_3_WARP_CUTSCENE: 0x59, 3
    RINGING_BELL_AND_HYRULE_1_CUTSCENE: 0x59, 4
    WIND_GODS_ARIA_CUTSCENE: 0x59, 5
    EARTH_GODS_LYRIC_CUTSCENE: 0x59, 6
    WATCHED_MEETING_KORL_CUTSCENE: 0x5A, 0
    MAKAR_IN_WIND_TEMPLE_ENTRANCE: 0x5A, 1
    MEDLI_IN_EARTH_TEMPLE_ENTRANCE: 0x5A, 2
    PEARL_TOWER_CUTSCENE: 0x5A, 7
    DID_SWORD_FIGHTING_TUTORIAL: 0x5B, 4
    DID_EARLY_SWORD_FIGHTING_TUTORIAL: 0x5B, 6
    TALKED_TO_GREAT_FAIRY_ON_OUTSET: 0x5C, 4
    TALKED_TO_ZILL_ON_OUTSET_WEST: 0x5D, 0
    TALKED_BAITO_OUTSIDE_DRI_AFTER_DRC: 0x5D, 1
    TALKED_TO_ABE_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x5D, 6
    SAW_SHIELD_IS_MISSING: 0x5E, 1
    WATCHED_DESCENDING_DOWN_TO_HYRULE_2_CUTSCENE: 0x5E, 7
    WATCHED_TEXT_AFTER_FIRE_AND_ICE_ARROWS_CUTSCENE: 0x5F, 7
    HAS_SEEN_INTRO: 0x61, 4
    MIGHTY_DARKNUTS_SPAWNED: 0x61, 5
    TALKED_TO_STURGEON_ON_OUTSET_AFTER_HELMAROC: 0x63, 2
    TALKED_TO_STURGEON_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x63, 3
    COLORS_IN_HYRULE: 0x64, 1
    WATCHED_COURTYARD_CUTSCENE: 0x64, 2
    ENTERED_HYRULE_1_WARP_AND_LOWERED_ELECTRICAL_BARRIER: 0x64, 4
    TALKED_TO_KORL_POST_TOWER_CUTSCENE: 0x64, 6
    MOVED_STATUE_IN_HYRULE: 0x64, 5
    WATCHED_FF2_GANONDORF_CUTSCENE: 0x65, 4
    TALKED_TO_DEKU_TREE_AFTER_FARORES_PEARL_CUTSCENE: 0x65, 6
    HYRULE_3_ELECTRICAL_BARRIER_CUTSCENE_1: 0x65, 7
    TRIALS_JALHALLA: 0x65, 0
    TRIALS_KALLE_DEMOS: 0x65, 1
    TRIALS_GOHMA: 0x65, 2
    SAW_DRC_BEATEN_CUTSCENE: 0x65, 3
    TRIALS_MOLGERA: 0x66, 7
    PULLED_MASTER_SWORD_IN_HYRULE_1_SWINGING_CUTSCENE: 0x66, 2
    TALKED_TO_SUE_BELLE_WHEN_VISITING_OUTSET_A_SECOND_TIME: 0x66, 6
    WATCHED_MEDLI_DRAGON_ROOST_CUTSCENE: 0x67, 4
    TALKED_TO_LOCKED_PIRATE_SHIP_DOOR: 0x67, 5
    HYRULE_1_ELECTRICAL_BARRIER_DEACTIVATED: 0x67, 6
    FF3_TO_HYRULE_WARP_ACTIVE: 0x69, 1
    DEFEATED_KALLE_DEMOS: 0x69, 6
    DEFEATED_GOHMA: 0x69, 7
    ENTER_GRANDMAS_ROOM_DURRING_ENDLESS_NIGHT: 0x6A, 0
    ARRIVING_AT_OUTSET_AFTER_BOMBS: 0x6A, 4
    DONT_SHOW_WEAPONS: 0x6B, 6
    TALKED_TO_KORL_LEAVING_OUTSET_BEFORE_NAYRUS_PEARL: 0x6B, 7
}

impl Flag {
    pub fn activate(self) {
        let Flag(addr, value) = self;
        let ptr = ptr::<u8>(addr);
        unsafe {
            *ptr |= value;
        }
    }

    pub fn deactivate(self) {
        let Flag(addr, value) = self;
        let ptr = ptr::<u8>(addr);
        unsafe {
            *ptr &= 0xFF ^ value;
        }
    }

    pub fn is_active(self) -> bool {
        let Flag(addr, mask) = self;
        let value = read::<u8>(addr);
        value & mask != 0
    }

    pub fn toggle(self) {
        if self.is_active() {
            self.deactivate()
        } else {
            self.activate()
        }
    }
}
