[package]

name = "rand"
version = "0.3.14"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rand"
documentation = "https://doc.rust-lang.org/rand"
homepage = "https://github.com/rust-lang/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]

[dependencies]
libtww = { path = "../.." }

[dev-dependencies]
log = "0.3.0"
