[package]
name = "chrono"
version = "0.2.25"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Date and time library for Rust"
homepage = "https://github.com/lifthrasiir/rust-chrono"
documentation = "https://lifthrasiir.github.io/rust-chrono/"
repository = "https://github.com/lifthrasiir/rust-chrono"
keywords = ["date", "time", "calendar"]
readme = "README.md"
license = "MIT/Apache-2.0"

[lib]
name = "chrono"

[dependencies]
libtww = { path = "../.." }
time = { path = "../time" }
num-integer = { path = "../num/integer", default-features = false }
num-traits = { path = "../num/traits", default-features = false }